[package]
name = "kat_extension"
version = "0.1.0"
authors = ["Katalam"]
edition = "2018"

[lib]
name = "kat_10thmods"
crate-type = ["cdylib"]

[dependencies]
libc = "*"
lazy_static = "1.0.0"
enigo = "0.0.12"
discord-rpc-client = "^0.2"
webbrowser = "*"
