name = "KAT 10th Basemods"
prefix = "KBM"
author = "Katalam"
version = "0.1.0.0"
files = ["mod.cpp", "logo_kbm_ca.paa"]
include = ["./include", "LICENSE"]
#releasebuild = ["@zip KBM"]
sigversion = 3
exclude = ["*.psd", "*.png", "*.tga", "*.blend", "*.blend1", "*.fbx", "*.xcf", "*.obj", "*.jpg", "*.fzz", "*.mtl", "*.spp", "*.painter_lock"]
