name = "KAT 10th Basemods";
dir = "@KBM";
author = "Katalam";
picture = "logo_kbm_ca.paa";
actionName = "Github";
action = "https://github.com/Katalam/KBM";
logo = "logo_kbm_ca.paa";
logoOver = "logo_kbm_ca.paa";
overviewPicture = "logo_kbm_ca.paa";
