class CSG {
	id = 2;
	idType = 0;
	side = "west";
	type = "Maritime";
	commander = "Kilcline Jr.";
	commanderRank = "General";
	text = "%1 Carrier Strike Group";
	textShort = "%1 CSG";
	subordinates[] = {CSG_0,CSG_1,CSG_2,CSG_3,CSG_4,CSG_5,CSG_6,CSG_7,CSG_8,CSG_9,CSG_10};
	description = "";
	insignia = QPATHTOF(data\2csg.paa);
	texture = QPATHTOF(data\2csg.paa);
	color[] = {255,255,255,1};
	//assets[] = {{"Land_Carrier_01_base_F"}, {"Land_Destroyer_01_base_F"}, {"Land_Destroyer_01_base_F"}, {"Submarine_01_F"}, {"Submarine_01_F"}, {"Submarine_01_F"}, {"Submarine_01_F"}};
};
	class CSG_0 {
		id = 1;
		idType = 0;
		side = "west";
		type = "Maritime";
		commander = "Kilcline Jr.";
		commanderRank = "General";
		text = "USS George H.W. Bush";
		textShort = "USS George H.W. Bush";
		subordinates[] = {};
		description = "";
	};
	class CSG_1 {
		id = 1;
		idType = 0;
		side = "west";
		type = "Maritime";
		commander = "NATOMen";
		commanderRank = "Colonel";
		text = "USS Anzio";
		textShort = "USS Anzio";
		subordinates[] = {};
		description = "";
	};
	class CSG_2 {
		id = 1;
		idType = 0;
		side = "west";
		type = "Maritime";
		commander = "NATOMen";
		commanderRank = "Colonel";
		text = "USS Gettysburg";
		textShort = "USS Gettysburg";
		subordinates[] = {};
		description = "";
	};
	class CSG_3 {
		id = 1;
		idType = 0;
		side = "west";
		type = "Maritime";
		commander = "NATOMen";
		commanderRank = "Colonel";
		text = "USS Truxtun";
		textShort = "USS Truxtun";
		subordinates[] = {};
		description = "";
	};
	class CSG_4 {
		id = 1;
		idType = 0;
		side = "west";
		type = "Maritime";
		commander = "NATOMen";
		commanderRank = "Colonel";
		text = "USS Mitscher";
		textShort = "USS Mitscher";
		subordinates[] = {};
		description = "";
	};
	class CSG_5 {
		id = 46;
		idType = 0;
		side = "west";
		type = "Helicopter";
		commander = "NATOMen";
		commanderRank = "Major";
		text = "%2 Maritime Strike %1";
		textShort = "'Grandmasters'";
		subordinates[] = {};
		description = "";
		assets[] = {{"B_Heli_Transport_01_F"},{"B_Heli_Transport_01_F"},{"B_Heli_Transport_01_F"},{"B_Heli_Transport_01_F"}};
	};
	class CSG_6 {
		id = 213;
		idType = 0;
		side = "west";
		type = "Fighter";
		size = "Squadron";
		commander = "NATOMen";
		text = "%1 Strike %2 %3";
		textShort = "'Blacklions'";
		subordinates[] = {};
		description = "";
		assets[] = {{"B_Plane_Fighter_01_F"},{"B_Plane_Fighter_01_F"},{"B_Plane_Fighter_01_F"},{"B_Plane_Fighter_01_F"},{"B_Plane_Fighter_01_F"},{"B_Plane_Fighter_01_F"},{"B_Plane_Fighter_01_F"},{"B_Plane_Fighter_01_F"},{"B_Plane_Fighter_01_F"},{"B_Plane_Fighter_01_F"},{"B_Plane_Fighter_01_F"},{"B_Plane_Fighter_01_F"}};
	};
	class CSG_7 {
		id = 87;
		idType = 0;
		side = "west";
		type = "Fighter";
		size = "Squadron";
		commander = "NATOMen";
		text = "%1 Strike %2 %3";
		textShort = "'Blacklions'";
		subordinates[] = {};
		description = "";
		assets[] = {{"B_Plane_Fighter_01_F"},{"B_Plane_Fighter_01_F"},{"B_Plane_Fighter_01_F"},{"B_Plane_Fighter_01_F"},{"B_Plane_Fighter_01_F"},{"B_Plane_Fighter_01_F"},{"B_Plane_Fighter_01_F"},{"B_Plane_Fighter_01_F"},{"B_Plane_Fighter_01_F"},{"B_Plane_Fighter_01_F"}};
	};
	class CSG_8 {
		id = 31;
		idType = 0;
		side = "west";
		type = "Fighter";
		size = "Squadron";
		commander = "NATOMen";
		text = "%1 Strike %2 %3";
		textShort = "'Tomcatters'";
		subordinates[] = {};
		description = "";
		assets[] = {{"B_Plane_Fighter_01_F"},{"B_Plane_Fighter_01_F"},{"B_Plane_Fighter_01_F"},{"B_Plane_Fighter_01_F"},{"B_Plane_Fighter_01_F"},{"B_Plane_Fighter_01_F"},{"B_Plane_Fighter_01_F"},{"B_Plane_Fighter_01_F"},{"B_Plane_Fighter_01_F"},{"B_Plane_Fighter_01_F"},{"B_Plane_Fighter_01_F"},{"B_Plane_Fighter_01_F"}};
	};
	class CSG_9 {
		id = 15;
		idType = 0;
		side = "west";
		type = "Fighter";
		size = "Squadron";
		commander = "NATOMen";
		text = "%1 Strike %2 %3";
		textShort = "'Valions'";
		subordinates[] = {};
		description = "";
		assets[] = {{"B_Plane_Fighter_01_F"},{"B_Plane_Fighter_01_F"},{"B_Plane_Fighter_01_F"},{"B_Plane_Fighter_01_F"},{"B_Plane_Fighter_01_F"},{"B_Plane_Fighter_01_F"},{"B_Plane_Fighter_01_F"},{"B_Plane_Fighter_01_F"},{"B_Plane_Fighter_01_F"},{"B_Plane_Fighter_01_F"}};
	};
	class CSG_10 {
		id = 141;
		idType = 0;
		side = "west";
		type = "GeneralSupport";
		size = "Squadron";
		commander = "NATOMen";
		text = "%1 %3";
		textShort = "'Shadowhawks'";
		subordinates[] = {};
		description = "";
		assets[] = {{"B_T_VTOL_01_infantry_F"},{"B_T_VTOL_01_infantry_F"},{"B_T_VTOL_01_infantry_F"},{"B_T_VTOL_01_infantry_F"}};
	};
