PREP(addLoadoutMenu);
PREP(addRoleDescription);
PREP(applyPlayerLoadout);
PREP(applyVehicleLoadout);
PREP(canSwitch);
PREP(clearPlayerLoadout);
PREP(clearVehicleLoadout);
PREP(moduleAddLoadoutMenu3den);
PREP(switchGunbag);
