# main.yml
name: CI

on:
  push:
    branches:
      - master
  pull_request: ~

jobs:
  test-sqflint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: sqflint
        uses: arma-actions/sqflint@v1.0
